# Generated by Django 5.0.3 on 2024-04-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_trainee', to='enrollment.training'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='user_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
            ],
            options={
                'verbose_name': 'Trainee',
                'verbose_name_plural': 'Trainees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
    ]
