# Generated by Django 5.0.3 on 2024-05-12 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of registration.'),
        ),
    ]
