# Generated by Django 5.0.3 on 2024-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trans_num',
            field=models.CharField(error_messages={'unique': 'A user with that transaction already exists.'}, help_text='Required. bank unique transaction number.', max_length=20, null=True, unique=True, verbose_name='Transaction Number'),
        ),
    ]
