# Generated by Django 5.0.3 on 2024-05-22 07:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=3, help_text='Required. 12-digit character should start with 251 followed by either 9 or 7 then 7 digits', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number: should start with 251 and be followed by either 9 or 7 then 8 digits', regex='^251(7|9)\\d{8}')]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
