# Generated by Django 5.0.3 on 2024-05-22 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_otp_alter_user_phone_number_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Trainee',
                'verbose_name_plural': 'Trainees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', help_text='Required. 12-digit character should start with 251 followed by either 9 or 7 then 7 digits', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number: should start with 251 and be followed by either 9 or 7 then 8 digits', regex='^251(7|9)\\d{8}')]),
        ),
    ]
