# Generated by Django 5.0.3 on 2024-05-22 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_staff_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
