# Generated by Django 5.0.3 on 2024-05-29 02:19

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_preference_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trans_num',
            field=models.CharField(error_messages={'unique': 'A user with that transaction already exists.'}, help_text='Required. bank unique transaction number.', max_length=20, null=True, unique=True, validators=[account.validators.validate_unique_trans_num], verbose_name='Transaction Number'),
        ),
    ]
