# Generated by Django 5.0.3 on 2024-05-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_trans_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='bank',
            new_name='bank_options',
        ),
    ]
