# Generated by Django 5.0.3 on 2024-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_bank_preference_bank_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='bank_options',
        ),
        migrations.AddField(
            model_name='preference',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
