# Generated by Django 5.0.3 on 2024-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_preference_bank_options_preference_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Email of a user e.g., example@gmail.com', max_length=255, null=True, unique=True),
        ),
    ]
