# Generated by Django 5.0.3 on 2024-06-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_email'),
    ]

    operations = [
    ]
