# Generated by Django 5.0.3 on 2024-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
