# Generated by Django 5.0.3 on 2024-05-16 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_trans_num'),
        ('finance', '0004_alter_traineepayment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_num', models.CharField(error_messages={'unique': 'A payment with that transaction number already exists.'}, help_text="Required. Bank's unique transaction number.", max_length=20, null=True, unique=True, verbose_name='Transaction Number')),
                ('is_completed', models.BooleanField(default=False, help_text='Specifies if the payment is completed.', verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the payment was created.', verbose_name='Created At')),
                ('account_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_payments', to='finance.bankaccount', verbose_name='Bank Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', related_query_name='monthly_payment', to='account.trainee', verbose_name='Trainee')),
            ],
        ),
    ]
