# Generated by Django 5.0.3 on 2024-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineepayment',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Is Rejected'),
        ),
    ]
