# Generated by Django 5.0.3 on 2024-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_traineepayment_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Is Rejected'),
        ),
    ]
