# Generated by Django 5.0.3 on 2024-05-22 09:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_staff_alter_user_phone_number'),
        ('finance', '0007_monthlypayment_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaymentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(verbose_name='Opening Date')),
                ('closing_date', models.DateTimeField(verbose_name='Closing Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Monthly Payment Cycle',
                'verbose_name_plural': 'Monthly Payment Cycles',
            },
        ),
        migrations.AlterModelOptions(
            name='monthlypayment',
            options={'verbose_name': 'Monthly Payment', 'verbose_name_plural': 'Monthly Payments'},
        ),
        migrations.AlterModelOptions(
            name='traineepayment',
            options={'verbose_name': 'Trainee Payment', 'verbose_name_plural': 'Trainee Payments'},
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='traineepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_payments', related_query_name='%(class)s_payment', to='account.trainee', verbose_name='Trainee'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.monthlypaymentcycle', verbose_name='Payment Cycle'),
        ),
    ]
