# Generated by Django 5.0.3 on 2024-05-29 02:19

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_monthlypaymentcycle_alter_monthlypayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='trans_num',
            field=models.CharField(error_messages={'unique': 'A payment with that transaction number already exists.'}, help_text="Required. Bank's unique transaction number.", max_length=20, null=True, unique=True, validators=[account.validators.validate_unique_trans_num], verbose_name='Transaction Number'),
        ),
    ]
