# Generated by Django 5.0.3 on 2024-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_contact_first_name_contact_last_name'),
        ('finance', '0003_delete_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
