# Generated by Django 5.0.3 on 2024-05-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='training',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('Hizb And', 'Hizb And'), ('Derek And', 'Derek And')], max_length=255, unique=True),
        ),
    ]
