# Generated by Django 5.0.3 on 2024-05-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_register_date'),
        ('enrollment', '0005_enrollment_is_complete_alter_training_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='trainee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_training', to='account.trainee'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training',
            field=models.CharField(max_length=255, verbose_name='Training'),
        ),
    ]
