# Generated by Django 5.0.3 on 2024-05-15 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_training_trainee_alter_training_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='trainee',
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
