# Generated by Django 5.0.3 on 2024-04-15 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^251(7|9)\\d{8}', 'Invalid phone_number: should be 12 char and format of 251...')])),
                ('message', models.TextField()),
            ],
        ),
    ]
