# Generated by Django 5.0.3 on 2024-04-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_contact_delete_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactus',
        ),
    ]
